//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Cart
{
    public int ORDER_NUMBER { get; set; }
    public Nullable<int> CUSTOMER_ID { get; set; }
    public string PRODUCT_NAME { get; set; }
    public string PRODUCT_PRICE { get; set; }
    public string ORDER_DATE { get; set; }
    public string ORDER_TIME { get; set; }
}

public partial class Customer
{
    public int CUSTOMER_ID { get; set; }
    public string CUSTOMER_FNAME { get; set; }
    public string CUSTOMER_LNAME { get; set; }
    public string CUSTOMER_ADDRESS { get; set; }
    public string CUSTOMER_PHONE { get; set; }
    public string CUSTOMER_EMAIL { get; set; }
}

public partial class Product
{
    public int PRODUCT_ID { get; set; }
    public string PRODUCT_NAME { get; set; }
    public string PRODUCT_DESCRIPTION { get; set; }
    public string PRODUCT_PRICE { get; set; }
    public string PRODUCT_IMAGE { get; set; }
}
